### ISSUE TITLE
Data Export: Generate and send email

### ISSUE THREAD

**Issue by rmalecky** [rubyforgood/panda_app#8]
Email results for an observation set.
- Create a form to input recipient email address
- Generate body of the email based on the session info
- Generate attachment from observations (see issue 6)
- Send email

Test to see if emails can be sent synchronously, if not create tickets to create background worker

**Comment by christinaforney** [comment]
Uses https://github.com/mailgun/mailgun-ruby

**Comment by christinaforney** [comment]
This should be broken into client side and csv generation (lib/ObservationExporter) efforts. Attachment is already added to the email since the API for ObservationSession nests the Exporter. Email is sending.

To Do:
- Generate data -> CSV string in ObservationExporter
- Add form to client for sending email
